services:
  zakaty:
    image: cybrarist/zakaty:latest
#    build:
#      context: .
    ports:
      - 8080:80
    environment:
      DB_CONNECTION: sqlite
      # DB_HOST=127.0.0.1
      # DB_PORT=3306
      # DB_DATABASE=zakah
      # DB_USERNAME=root
      # DB_PASSWORD=
      APP_TIMEZONE: Asia/Dubai
      APP_URL: "http://localhost:8080"
      ASSET_URL: "http://localhost:8080"
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_USERNAME: "email@gmail.com"
      MAIL_PASSWORD: "app password"
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: "email@gmail.com"
      EXCHANGE_RATE_API_KEY: ""
      PRECIOUS_METAL_PRICE_API_KEY: ""

