<?php

namespace App\Filament\Pages\Auth;

use App\Enums\UserRoleEnum;
use App\Models\Currency;
use App\Models\User;
use Filament\Actions\Action;
use Filament\Facades\Filament;
use Filament\Forms\Components\Placeholder;
use Filament\Forms\Components\Select;

class Login extends \Filament\Pages\Auth\Login
{
    public function mount(): void
    {
        if (User::count() === 0) {
            redirect()->to('/register');
        }

        parent::mount(); // TODO: Change the autogenerated stub
    }
}
